version: "3.9" # opsiyonel.

services:

  frontend:
    # container_name: frontend # (default:key)
    image: "docker-compose-frontend" # image_name
    build: ./FE-StockAPI # Dockerize edilecek klasör (dockerfile)
    ports:
      # dış/iç port numaraları
      - 5173:5173
      - 3000:5173
      - 80:5173
    restart: on-failure # hata anında tekrar çalıştır.
    depends_on:
      # önce aşağıdakileri çalıştır.
      - backend # aşağıda tanımlandı.

  backend:
    # container_name: backend # (default:key)
    image: "docker-compose-backend" # image_name
    build: ./BE-StockAPI # Dockerize edilecek klasör (dockerfile)
    ports:
      # dış/iç port numaraları
      - 8000:8000
    restart: on-failure # hata anında tekrar çalıştır.